apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devopshub
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 138035228373.dkr.ecr.eu-north-1.amazonaws.com/devopshub/backend:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: devopshub-config
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: devopshub-secret
                  key: JWT_SECRET
          resources:
             requests:
             cpu: "100m"
             memory: "256Mi"
             limits:
             cpu: "300m"
             memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 20
